services:
  web:
    build: .
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    volumes:
      - .:/app       # Mount the project directory for live updates during development
    environment:
      - APP_ENV=development  # Environment variables (can be customized)